FROM mattermost/mattermost-team-edition:latest

# Set environment variables
ENV MM_SQLSETTINGS_DRIVERNAME=postgres
ENV MM_SERVICESETTINGS_LISTENADDRESS=":8000"
ENV MM_SERVICESETTINGS_ENABLELOCALMODE=false
ENV MM_SERVICESETTINGS_ENABLEDEVELOPER=false
ENV MM_SERVICESETTINGS_ENABLEINCOMINGWEBHOOKS=true
ENV MM_SERVICESETTINGS_ENABLEOUTGOINGWEBHOOKS=true
ENV MM_SERVICESETTINGS_ENABLECOMMANDS=true
ENV MM_SERVICESETTINGS_ENABLEBOTACCOUNTCREATION=false
ENV MM_BOTSETTINGS_ENABLE=false

# Expose port
EXPOSE 8000

# Use the correct command for Mattermost
CMD ["mattermost"]
